name: Android Release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Dependencies
      run: |
        npm install
        npm install --save @capacitor/core @capacitor/cli
        npm install @capacitor/android
    - name: React App
      run: |
        npm run build
    - name: Android APK
      run: |
        npx cap init
        npx cap add android
        npx cap copy
        cd android
        chmod +x ./gradlew
        ./gradlew assembleDebug
    - name: Rename APK
      run: |
        mv android/app/build/outputs/apk/debug/app-debug.apk app_aqp.apk
    - name: Verify APK
      run: |
        ls -R android/app/build/outputs/apk/
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app_aqp
        path: ./app_aqp.apk

  release:
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app_aqp

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Clemente }}
        with:
          tag_name: release-${{ github.sha }}
          release_name: Release ${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.Clemente }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./app_aqp.apk
          asset_name: app_aqp.apk
          asset_content_type: application/vnd.android.package-archive
